# Run from project root: Rscript.exe --vanilla R/timeseries/run.R
# No network access, package installation, or modification of source data.
main <- function() {
  # The host exports a Linux-style C.UTF-8 locale that Windows R cannot use.
  # Select a UTF-8 CTYPE for this process before reading Indonesian text.
  if (.Platform$OS.type == "windows") {
    locale <- suppressWarnings(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
    if (!nzchar(locale)) stop("Locale UTF-8 untuk Windows R tidak tersedia.", call. = FALSE)
  }
  assert_root <- file.exists("Data Fix - DATA.csv") && file.exists("data/lampung_panel_clean.csv")
  if (!assert_root) stop("Jalankan dari root project C:/Akbar/PSD.", call. = FALSE)
  if (dir.exists(".library")) .libPaths(c(normalizePath(".library"), .libPaths()))
  source("R/timeseries/analysis.R", encoding = "UTF-8")
  source("R/timeseries/methodology.R", encoding = "UTF-8")
  source("R/timeseries/checks.R", encoding = "UTF-8")
  source("R/timeseries/reconciliation.R", encoding = "UTF-8")
  source("R/timeseries/environment.R", encoding = "UTF-8")
  source("R/timeseries/plots.R", encoding = "UTF-8")
  source("R/timeseries/report.R", encoding = "UTF-8")
  assert(requireNamespace("ggplot2", quietly = TRUE), "ggplot2 belum tersedia; pipeline tidak memasang package otomatis.")
  verify_environment()
  out <- "output/timeseries"
  dir.create(out, recursive = TRUE, showWarnings = FALSE)
  log <- file(file.path(out, "run.log"), open = "wt", encoding = "UTF-8")
  sink(log, split = TRUE)
  on.exit({sink(); close(log)}, add = TRUE)
  cat("ANALISIS DERET WAKTU IKP LAMPUNG\n")
  cat("Waktu eksekusi UTC:", format(Sys.time(), tz = "UTC", usetz = TRUE), "\n")
  protected <- c("Data Fix - DATA.csv", "data/lampung_panel_clean.csv", "laporan_draft.md", "LAPORAN_rev.md",
    list.files("R", pattern = "^[0-9]{2}_.*[.]R$", full.names = TRUE), list.files("review/sources", full.names = TRUE),
    "review/timeseries/rekonsiliasi_nilai.csv", "review/timeseries/dependensi.csv", "renv.lock")
  before <- tools::md5sum(protected)
  inputs <- data.frame(file = protected[1:2],
    sha256 = vapply(protected[1:2], sha256, character(1)),
    sha256_teks_lf = vapply(protected[1:2], sha256, character(1), canonical_text = TRUE))
  expected <- c("45aed9ed91043495c9edd63dca80db0af9039bbe6362a17aa541630ab1d41196", "0812042e7fba6261edc03ffc483eea73191c22e9fe0715d73be297eb8aa6c3f1")
  assert(identical(unname(inputs$sha256_teks_lf), expected), "Isi input berbeda dari versi data yang diaudit (hash teks LF). Periksa sumber sebelum menjalankan analisis.")
  d <- read.csv("data/lampung_panel_clean.csv", colClasses = c(kode = "character"), fileEncoding = "UTF-8")
  validate_panel(d)
  raw <- read_raw_ikp("Data Fix - DATA.csv")
  validate_panel(raw)
  raw <- raw[order(raw$kode, raw$tahun), ]; clean <- d[order(d$kode, d$tahun), ]
  assert(identical(raw$kode, clean$kode) && identical(raw$kabupaten, clean$kabupaten) && all(raw$tahun == clean$tahun) &&
    max(abs(raw$ikp - clean$ikp)) < 1e-10, "IKP/identitas raw dan clean berbeda.")
  cat("Validasi: 105 observasi, 15 wilayah, 7 tahun; raw dan clean cocok 105/105.\n")
  audit <- methodology_audit()
  run_checks(d, audit)
  original <- d
  original_discrepancies <- source_discrepancies(d, "review/sources/lampungprov_ikp_kabkota_2019-2024.csv")
  ledger <- read.csv("review/timeseries/rekonsiliasi_nilai.csv", fileEncoding = "UTF-8")
  d <- reconcile_values(d, original_discrepancies, ledger)
  run_reconciliation_checks(original, original_discrepancies, ledger, audit)
  sensitivity_values <- value_sensitivity(original, d, original_discrepancies, audit)
  d <- attach_methodology(d, audit)
  changes <- annual_changes(d)
  summaries <- region_summaries(d)
  dispersion <- county_dispersion(d)
  predictions <- backtest(d)
  sensitivity_forecasts <- forecast_sensitivity(predictions)
  accuracy_region <- forecast_accuracy(predictions, c("kode", "kabupaten", "tipe", "metode"))
  accuracy_group <- forecast_accuracy(predictions, c("tipe", "metode"))
  accuracy_year <- forecast_accuracy(predictions, c("tipe", "tahun_target", "metode"))
  discrepancies <- source_discrepancies(d, "review/sources/lampungprov_ikp_kabkota_2019-2024.csv")
  valid_changes <- sum(is.finite(changes$perubahan_poin))
  valid_predictions <- sum(is.finite(predictions$ramalan))
  assert(nrow(changes) == 90L && valid_changes == 51L, "Jumlah perubahan tidak sesuai kebijakan batas sumber.")
  assert(nrow(predictions) == 90L && valid_predictions == 12L, "Jumlah ramalan tidak sesuai kebijakan batas sumber.")
  assert(sum(original_discrepancies$cocok) == 85L && sum(discrepancies$cocok) == 86L && nrow(discrepancies) == 90L, "Hasil pencocokan sumber provinsi berubah.")
  csv <- function(x, name) write.csv(x, file.path(out, paste0(name, ".csv")), row.names = FALSE, fileEncoding = "UTF-8", na = "")
  csv(d, "data_analisis")
  csv(audit, "audit_metodologi")
  csv(discrepancies, "audit_sumber_provinsi")
  csv(discrepancies[!discrepancies$cocok, ], "selisih_sumber_provinsi")
  csv(original_discrepancies, "audit_sumber_provinsi_asal")
  csv(ledger, "rekonsiliasi_nilai")
  csv(sensitivity_values, "sensitivitas_nilai")
  csv(sensitivity_forecasts, "sensitivitas_tahun_uji")
  csv(changes, "perubahan_tahunan")
  csv(summaries, "ringkasan_wilayah_per_segmen")
  csv(dispersion, "kesenjangan_kabupaten")
  csv(predictions, "backtest_detail")
  csv(accuracy_region, "akurasi_per_wilayah")
  csv(accuracy_group, "akurasi_per_jenis_wilayah")
  csv(accuracy_year, "akurasi_per_tahun")
  csv(inputs, "hash_input_sha256")
  for (name in c("data_analisis", "perubahan_tahunan", "backtest_detail")) {
    exported <- read.csv(file.path(out, paste0(name, ".csv")), fileEncoding = "UTF-8")
    expected_n <- switch(name, data_analisis = 105L, perubahan_tahunan = 90L, backtest_detail = 90L)
    assert(nrow(exported) == expected_n, paste("Ekspor CSV tidak lengkap:", name))
  }
  cat("Perubahan: ", valid_changes, " dihitung; ", nrow(changes) - valid_changes, " dikecualikan.\n", sep = "")
  cat("Backtest: ", valid_predictions, " ramalan kota; ", nrow(predictions) - valid_predictions, " kandidat kabupaten tidak diestimasi.\n", sep = "")
  print(accuracy_group, row.names = FALSE)
  cat("Rekonsiliasi: 5 keputusan; 1 koreksi di salinan analisis. Sumber provinsi: asal 85/90; analisis 86/90 cocok.\n")
  make_figures(d, changes, summaries, dispersion, predictions, accuracy_region, out)
  write_report(d, audit, changes, summaries, dispersion, predictions, accuracy_region, accuracy_group, accuracy_year, discrepancies, inputs,
    ledger, original_discrepancies, sensitivity_values, sensitivity_forecasts)
  after <- tools::md5sum(protected)
  assert(identical(before, after), "Ada input/arsip yang berubah selama eksekusi.")
  csv(data.frame(file = protected, md5_sebelum = unname(before), md5_sesudah = unname(after), identik = before == after), "integritas_arsip")
  code_files <- list.files("R/timeseries", pattern = "[.]R$", full.names = TRUE)
  csv(data.frame(file = code_files, md5 = unname(tools::md5sum(code_files))), "versi_kode")
  writeLines(capture.output(sessionInfo()), file.path(out, "session_info.txt"), useBytes = TRUE)
  cat("LULUS: seluruh data dan arsip lama identik; CSV berhasil dibaca ulang.\n")
  cat("SELESAI: LAPORAN_deret_waktu.md dan output/timeseries/.\n")
}

tryCatch(main(), error = function(e) {
  message("PIPELINE GAGAL: ", conditionMessage(e))
  stop(e)
})
